Algoritmo "EXERCICIO7-I"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Exercícios de Lógica (Capítulo 07.)
// Autoras    :   Aline Gallo, Gabriela Camargo e Giovanna Gomes
// Data atual  : 07/05/2022
Var
// Seção de Declarações das variáveis
numero : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite um numero: ")
leia(numero)
escreval("O seu numero ao quadrado é ",numero*numero)

Fimalgoritmo